version: '3.1'
services:

  stats-server:
    build: stat-service/stat-server
    image: ewm-stat-server
    container_name: ewm-stat-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stat
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    restart: on-failure

  stats-db:
    image: postgres:14-alpine
    container_name: postgres-ewm-stat-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stat
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - /var/lib/db/data/ewm-stat

  ewm-service:
    build: main-service
    image: ewm-main-service
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SERVICE_STATSERVICE_URI=http://stats-server:9090
    restart: on-failure

  ewm-db:
    image: postgres:14-alpine
    container_name: postgres-ewm-main-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - /var/lib/db/data/ewm-main
